### ISSUE TITLE
Quote Widget

### ISSUE THREAD

**Issue by FaustCelaj** [Levi-Man/camel_daily_organizer#12]
The quote widget should resemble the following. The quote should be saved to local storage so that when a user refreshes it will not disappear.

We can have a generate new quote button that refreshes the quote with a new randomly generated one.

![Image](https://github.com/Levi-Man/camel_daily_organizer/assets/149631014/9cabc65e-7960-48be-b15d-503b62620c82)

Information we can pull:
- full quote
- Author

good to have extras
- year
- the topic of the quote (ex. history, science, philosophy, etc)
- these can be associated in a popup modal when the user clicks view more detail

**Comment by Levi-Man** [comment]
The API doesn't supply additional information on the quotes, but we can implement the other features such as generate quote and save to local storage.

**Comment by Levi-Man** [comment]
Done implementing the "New Quote" button and save to local storage. It saves the last loaded quote and author when the page is opened or refreshed. When the user clicks new quote, it generates a new random quote that then overwrites what was previously saved in local storage and that new quote-author combo persist on the page.
