### ISSUE TITLE
write JS for api2 - pexels

### ISSUE THREAD

**Issue by Levi-Man** [Levi-Man/camel_daily_organizer#16]
Research what the API can pull 

look for the image URL link so we can integrate changing images in our grid or header section
look for how to generate a search and show results
every time a user saves/updates an image can be saved to local storage

**Comment by FaustCelaj** [comment]
API is functioning as intended, when hitting search it shows images for the text a user input

next steps
- create an edit button
- edit button will open up a modal where users can search for an image
- once an image is found the selected image url can replace the existing image url to "change the photo"
- when a user saves the changes it will be sent to local storage to keep the new image even after a reload
- test this with the solo image block then move on to implement it to the grid
