### ISSUE TITLE
Check for bugs

### ISSUE THREAD

**Issue by FaustCelaj** [Levi-Man/camel_daily_organizer#46]
Check if everything operates the way it is intended
- widgets display the information correctly when first loading in
- refreshing page does not affect any information saved to local storage
- modals load everything correctly including on mobile
- refresh or changes of other modals do not affect any of the other dynamically loaded content

**Comment by Levi-Man** [comment]
1.  restyle top banner modal
2.  remove extra solo image 
3.  implement default quote upon first load
4.  restyle top banner button

**Comment by Levi-Man** [comment]
done
